augmentation:
  max_blur_kernel: 9
  min_blur_kernel: 5
  noise_level: 0.5
blobs:
  enabled: true
  max_alpha: 1.0
  max_size: 0.25
  max_stretch: 2.5
  min_alpha: 0.7
  min_size: 0.05
  min_stretch: 1.0
  num_blobs: 5
dataset:
  image_size: 128
  num_images: 300
  path: square_segmentation_dataset
  train_ratio: 0.7
  val_ratio: 0.15
random_seed: 42
square:
  max_rotation: 45
  max_size: 0.6
  min_rotation: -45
  min_size: 0.2
visualization:
  num_examples: 3
